### PR TITLE
Replace java logging with Log4j

### LINKED ISSUE #109: Fix error logs in Security Analytics
## Description
Currently, SAP is raising several error logs we need to fix, also our logs in general are noisy and difficult to read. When an error occurs locating the reason and the logs is hard since we have:
- Not clear logs
- Some print the whole trace
- Excessive logging for some things
- Lack of logging for other errors

The objective is to clean up the existing error logs, standardize their format, and ensure they provide enough information and clearly

**Logs example**
``` log
[2026-04-09T10:45:14,371][ERROR][o.o.s.c.JoinEngine       ] [wazuh-indexer] [CORRELATIONS] Exception encountered while searching correlation rule index for finding id 17939542-1599-4367-a51e-86d26e750044
[2026-04-09T10:45:14,378][ERROR][o.o.s.t.TransportCorrelateFindingAction] [wazuh-indexer] Exception occurred while processing correlations for monitor id v1SRcZ0B7w1eaAUvMtQx and finding id 894dda12-b634-4672-97bc-77bd8ca74e2f
[2026-04-09T10:45:14,378][ERROR][o.o.s.u.SecurityAnalyticsException] [wazuh-indexer] Security Analytics error: Cannot invoke "Object.toString()" because the return value of "java.util.Map.get(Object)" is null
[2026-04-09T10:45:14,379][ERROR][o.o.s.t.TransportCorrelateFindingAction] [wazuh-indexer] Exception occurred while processing correlations for monitor id v1SRcZ0B7w1eaAUvMtQx and finding id 5c26fa7e-af77-49e2-9f78-bbb11fcf986e
[2026-04-09T10:45:14,379][ERROR][o.o.s.t.TransportCorrelateFindingAction] [wazuh-indexer] Exception occurred while processing correlations for monitor id v1SRcZ0B7w1eaAUvMtQx and finding id 596cb8df-a412-4253-a93d-d8adaef0daba
[2026-04-09T10:45:14,379][ERROR][o.o.s.t.TransportCorrelateFindingAction] [wazuh-indexer] Exception occurred while processing correlations for monitor id v1SRcZ0B7w1eaAUvMtQx and finding id c9aa5a4a-ca8a-4b69-85bd-f3710f2e1a88
```

```log
[2026-04-13T13:22:06,809][ERROR][c.w.c.ContentManagerPlugin] [wazuh-indexer] Error scheduling Catalog Sync Job: No shard available for [get [.wazuh-content-manager-jobs][wazuh-catalog-sync-job]: routing [null]]
[2026-04-13T13:22:06,813][ERROR][o.o.i.i.ManagedIndexCoordinator] [wazuh-indexer] get managed-index failed: NoShardAvailableActionException[No shard available for [org.opensearch.action.get.MultiGetShardRequest@1378d607]]
```

### PR DESCRIPTION
**Pull request by QU3B1M**
### Description
Fix misleading WARN-level log messages at cluster startup:

- **WCSFieldValidator**: Replace `java.util.logging` (JUL) with Log4j2. JUL output goes to stderr, which OpenSearch captures as `[WARN][stderr]`, causing even INFO-level messages to appear as warnings. Now uses the same Log4j2 framework as the rest of the codebase.
- **SecurityAnalyticsPlugin**: Include the exception in the LogType config index initialization failure log. Previously the WARN message omitted the cause, making it impossible to diagnose why initialization failed.

### Issues Resolved
Closes #109

### CODE REVIEW

File: src/main/java/org/opensearch/securityanalytics/rules/objects/WCSFieldValidator.java [hunk 1]
```diff
@@ -94,7 +95,7 @@ public static void initFromIndexMetadata(IndexMetadata indexMetadata) {
 
         wcsFields.set(Collections.unmodifiableSet(fields));
 
-        log.info("WCS field validator initialized with " + fields.size() + " fields");
+        log.info("WCS field validator initialized with {} fields", fields.size());
```
Comment (Jorgesnchz) [inline src/main/java/org/opensearch/securityanalytics/rules/objects/WCSFieldValidator.java]: This could be a debug log

File: src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java [hunk 2]
```diff
@@ -566,7 +566,7 @@ public void onResponse(Void unused) {
 
                     @Override
                     public void onFailure(Exception e) {
-                        log.warn("Failed to initialize LogType config index and builtin log types");
+                        log.warn("Failed to initialize LogType config index and builtin log types", e);
```
Comment (Jorgesnchz) [inline src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java]: This will print the whole trace, it should be `e.getMessage()`

File: src/main/java/org/opensearch/securityanalytics/rules/objects/WCSFieldValidator.java (hunk 1 above)
Comment (Jorgesnchz) [reply src/main/java/org/opensearch/securityanalytics/rules/objects/WCSFieldValidator.java]: Changed in e27155e659b463a591c3162a6f1b6a5bbfbf1a25

File: src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java (hunk 2 above)
Comment (Jorgesnchz) [reply src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java]: Changed in e27155e659b463a591c3162a6f1b6a5bbfbf1a25

**Review by Jorgesnchz — APPROVED** [review]

**Review by AlexRuiz7 — APPROVED** [review]
